// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenDataViewerOld.Controllers;

namespace OpenDataViewerOld.Migrations
{
    [DbContext(typeof(DocumentContext))]
    [Migration("20181215195135_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OpenDataViewerOld.Controllers.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Identifier");

                    b.Property<string>("Organization");

                    b.Property<string>("Title");

                    b.Property<string>("Topic");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("OpenDataViewerOld.Controllers.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<int>("DocumentId");

                    b.Property<string>("Format");

                    b.Property<string>("Source");

                    b.HasKey("FileId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("OpenDataViewerOld.Controllers.File", b =>
                {
                    b.HasOne("OpenDataViewerOld.Controllers.Document", "Document")
                        .WithOne("File")
                        .HasForeignKey("OpenDataViewerOld.Controllers.File", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
